### ISSUE TITLE
databinding missing ?

### ISSUE THREAD

**Issue by Darlio** [gSrikar/VolleyRequest#1]
Hello,

Thank you for great insight !!! Did I miss anything or is there missing :
com.gsrikar.volleyrequest.databinding.ActivityLoginBinding

With my very best regards,

Daric

**Comment by gSrikar** [comment]
Hi Darlio,

The project uses [View Binding](https://developer.android.com/topic/libraries/view-binding), a shorter version of [Data Binding Library](https://developer.android.com/topic/libraries/data-binding) that helps replace `findViewById` calls.

It is available in the latest versions of Android Studio. For more details on `ViewBinding` you can check the article I've written on How to add [View Binding](https://www.gsrikar.com/2020/02/view-binding-replace-findviewbyid.html).

This library is not for all developers, it is only for the ones that are interested to have limited functionalities of Data Binding and not worry about the added size.

**Comment by Darlio** [comment]
That is GREAT !!!! Thank you !!!!!
